import Sidebar from "@/components/layouts/Sidebar";
import "../globals.css";
import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import Header from "@/components/layouts/Header";
import { Toaster } from "@/components/ui/toaster";
import NextAuthProvider from "@/context/NextAuthProvider";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "../api/auth/[...nextauth]/route";
import Navbar from "../../components/menu/nav-bar";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  // if (session === null) {
  //   return redirect("/");
  // }

  return (
    <html lang="en">
      <body className={epilogue.className}>
        <main>
          <NextAuthProvider>
            <Navbar />
            {/* <Header /> */}
            {children}
          </NextAuthProvider>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
