import Sidebar from "@/components/layouts/Sidebar";
// import "../globals.css";
import "../../../app/globals.css";
import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import Header from "@/components/layouts/Header";
import { Toaster } from "@/components/ui/toaster";
import NextAuthProvider from "@/context/NextAuthProvider";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "../../api/auth/[...nextauth]/route";
import Navbar from "@/components/menu/nav-bar";
import { BurgerMenu } from "@/components/menu/burgermenu";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  if (session === null) {
    return redirect("/");
  }

  return (
    <html lang="en">
      <body className={epilogue.className}>
        <main>
          <NextAuthProvider>
            <div className="border-t">
              <div className="bg-background">
                <div className="flex flex-row">
                  <div className="hidden lg:block w-[18%]">
                    <Sidebar />
                  </div>

                  <div className="col-span-3 overflow-auto lg:col-span-5 lg:border-l w-full lg:w-[82%]">
                    <div className="px-6 py-6 lg:px-8">
                      <div className=" md:hidden">
                        <Navbar />
                      </div>
                      <Header />
                      {children}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </NextAuthProvider>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
